import type { Metadata } from "next";
import "./globals.css";
import { storeRoot } from "../lib/env";
import { storeHasSyntheticRuns, withStore } from "../lib/store";

export const metadata: Metadata = {
  title: "invariant",
  description: "Agent behavioural consistency: leaderboard, run matrices, trace diffs, trends.",
};
export const dynamic = "force-dynamic";

function SyntheticBanner() {
  const root = storeRoot();
  const info = withStore(root, (s) => {
    if (s.kind !== "ok") return null;
    if (s.demo) return { demo: s.demo };
    return storeHasSyntheticRuns(s.store) ? { demo: null } : null;
  });
  if (!info) return null;
  return (
    <div className="synthetic-banner" role="note">
      <strong>SYNTHETIC DATA.</strong>{" "}
      {info.demo
        ? `This whole store was generated by ${info.demo.generator} (${info.demo.created_at.slice(0, 19).replace("T", " ")}Z): every run was driven by a scripted stand-in, not a model. Nothing here is a finding about any model.`
        : "This store contains runs driven by a scripted stand-in, not a model. They are labelled SYNTHETIC wherever they appear; nothing they show is a finding about any model."}
    </div>
  );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="topbar">
          <a className="brand" href="/">invariant</a>
          <nav>
            <a href="/">Leaderboard</a>
            <a href="/diff">Trace diff</a>
            <a href="/fingerprints">Fingerprints</a>
          </nav>
          <span className="store" title={storeRoot()}>
            store {storeRoot()} · read-only
          </span>
        </header>
        <SyntheticBanner />
        <main>{children}</main>
      </body>
    </html>
  );
}
